### ISSUE TITLE
Doesn't seem to be producing the correct output

### ISSUE THREAD

**Issue by treeder** [fnproject/fdk-node#7]
Deployed it to local server and the response body is [object Object].

**Comment by michael-w-williams** [comment]
I have encountered the same problem while testing the new node tutorial. Here is the data I collected.

Currently using:

```yaml
Client version:  0.4.66
Server version:  0.3.385
```

## What works

The `fn init --runtime node nodefn` command generates the following function:

```js
var fdk=require('@fnproject/fdk');

fdk.handle(function(input){
  var name = 'World';
  if (input.name) {
    name = input.name;
  }
  response = {'message': 'Hello ' + name}
  return response
})
```

This works fine with:

* `fn run`
* `echo -n '{"name":"Bob"}' | fn run`
* `fn call nodeapp /nodefn`

The function returns:

```json
{"message":"Hello World"}
```
or

```json
{"message":"Hello Bob"}
```

## Issue with Curl
However, when you call the function with curl you get a different result:

>`curl http://localhost:8080/r/nodeapp/nodefn`

returns:

```txt
[object Object]
```

So to see the headers I tried again with --raw and I get:

> `curl -iv --raw http://localhost:8080/r/nodeapp/nodefn`

returns

```yaml
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /r/nodeapp/nodefn HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Content-Length: 15
Content-Length: 15
< Content-Type: text/plain; charset=utf-8
Content-Type: text/plain; charset=utf-8
< Fn_call_id: 01C92WA4YH47WH200000000000
Fn_call_id: 01C92WA4YH47WH200000000000
< Xxx-Fxlb-Wait: 529.127504ms
Xxx-Fxlb-Wait: 529.127504ms
< Date: Tue, 20 Mar 2018 23:36:07 GMT
Date: Tue, 20 Mar 2018 23:36:07 GMT

<
* Connection #0 to host localhost left intact
[object Object]
```
An id is returned rather than JSON.

## Different Return Statement

Looking at the docs in the FDK-Node repo I noticed a different return statement for the function was used in the docs.

```js
var fdk=require('@fnproject/fdk');

fdk.handle(function(input){
  var name = 'World';
  if (input.name) {
    name = input.name;
  }
  response = {'message': 'Hello ' + name}
  return JSON.stringify(response)
})
```
Changing the return statement fixes the curl results. However, using `fn run` or `fn call` returns JSON in a sort of Java format:

```json
"{\"message\":\"Hello World\"}"
```

Any assistance you can give is appreciated. Thanks.
